FISH-1145 Command success checking for Windows and adjust Linux

diff --git a/appserver/packager/upgrade-tool/src/main/resources/glassfish/bin/rollbackUpgrade b/appserver/packager/upgrade-tool/src/main/resources/glassfish/bin/rollbackUpgrade
--- a/appserver/packager/upgrade-tool/src/main/resources/glassfish/bin/rollbackUpgrade
+++ b/appserver/packager/upgrade-tool/src/main/resources/glassfish/bin/rollbackUpgrade
@@ -81,11 +81,11 @@ do
 
         mv ${AS_INSTALL}/${i}/* ${AS_INSTALL}/${i}.new/
         if [ ! $? -eq 0 ]; then
-            # Check if the warning was a missing MQ directory
+            # Check if the warning was an empty MQ directory
             if [[ ! "${i}" == *"mq"* ]]; then
                 WARN=true
             else
-                echo "Ignoring error moving MQ directory to staged location, assuming this is a leftover empty directory from a previous payara distribution"
+                echo "Ignoring error moving empty MQ directory to staged location, assuming this is a leftover empty directory from a previous payara distribution"
             fi
         fi
 
@@ -96,7 +96,7 @@ do
             if [[ ! "${i}" == *"mq"* ]]; then
                 WARN=true
             else
-                echo "Ignoring error moving MQ directory to staged location, assuming this is a leftover empty directory from a previous payara distribution"
+                echo "Ignoring error moving missing MQ directory to staged location, assuming you're rolling back a payara-web distribution"
             fi
         fi
     fi
@@ -105,7 +105,12 @@ do
     if [ -d "${AS_INSTALL}/${i}.old" ]; then
         mv ${AS_INSTALL}/${i}.old/* ${AS_INSTALL}/${i}/
         if [ ! $? -eq 0 ]; then
-            WARN=true
+            # Check if the warning was an empty MQ directory
+            if [[ ! "${i}" == *"mq"* ]]; then
+                WARN=true
+            else
+                echo "Ignoring error moving empty old MQ directory to expected location, assuming this is a leftover empty directory from a previous payara distribution"
+            fi
         fi
     else
         mv ${AS_INSTALL}/${i}.old ${AS_INSTALL}/${i}
@@ -113,6 +118,8 @@ do
             # Check if the warning was a missing MQ directory
             if [[ ! "${i}" == *"mq"* ]]; then
                 WARN=true
+            else
+                echo "Ignoring error moving missing old MQ directory to expected location, assuming you're rolling back to a payara-web distribution"
             fi
         fi
     fi
@@ -120,13 +127,18 @@ do
     rm -rf ${AS_INSTALL}/${i}.old
 done
 
-${AS_INSTALL}/bin/asadmin reinstall-nodes "$@"
-if [ ! $? -eq 0 ]; then
-    WARN=true
+
+if [ ! -z "$WARN" ]; then
+    echo "A command didn't complete successfully! Check the logs and your current install. Skipping reinstallation of nodes, please run the reinstall-nodes ASadmin command if this is incorrect."
+else
+    ${AS_INSTALL}/bin/asadmin reinstall-nodes "$@"
+    if [ ! $? -eq 0 ]; then
+        WARN=true
+    fi
 fi
 
 if [ ! -z "$WARN" ]; then
-    echo "A command didn't complete successfully! Check the logs and run the rollbackUpgrade script if desired, otherwise please use the restore-domain ASadmin command to restore your desired domains."
+    echo "A command didn't complete successfully! Check the logs and your current install, please use the restore-domain ASadmin command to restore your desired domains if everything appears fine."
 else
     echo "Please use the restore-domain ASadmin command to restore your desired domains."
 fi
